config/routes.rb
CrazyJake::Application.routes.draw do

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, except: [:show]

  resources :complete_surveys, only: [:index, :create]

  resources :qr_codes, only: [:index]

  resources :customers do
    resources :surveys do
        member do
          post "card"
        end
      resources :reports, only: [:index]  do
        member do
          post 'reporting_fields'
        end
      end
      resources :questions do
        member do
          get 'down'
          get 'up'
        end
      end
      resources :reporting_fields, except: [:show]
    end
    resources :payments, only: [:index, :create]  do
      member do
        get 'paid'
      end
    end
  end

  root :to => "customers#index"

end

app/models/question.rb
class QuestionValidator < ActiveModel::Validator
  def validate(record)
    if (
          record.yes_no and (record.rating or record.free_form or record.customized) or
          record.rating and (record.yes_no or record.free_form or record.customized) or
          record.free_form and (record.yes_no or record.rating or record.customized) or
          record.customized and (record.yes_no or record.rating or record.free_form)
      )
      record.errors[:yes_no] << 'Only one question type may be selected per question'
    elsif (!record.yes_no and !record.rating and !record.free_form and !record.customized)
      record.errors[:yes_no] << 'A question type must be selected'
    elsif (record.customized and (!record.custom_values.present? or !record.custom_type))
      record.errors[:customized] << 'You must provide the available values and display type when selecting custom question'
    end
  end
end

class Question < ActiveRecord::Base
  belongs_to :survey

  validates :index, {presence: true, uniqueness: {scope: :survey_id, allow_blank: false },numericality: { greater_than: 0}}
  validates :text, { presence: true }
  validates :survey_id, { presence: true }
  validates_with QuestionValidator

  def custom_values_array
    custom_values ? custom_values.strip.split(/[\r\n]+/) : Array.new
  end

  def self.custom_types
    ["single selection","multiple selections","drop-down(single selection)"]
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy, :down, :up]
  before_filter :set_survey

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.where(survey_id: @survey.id).sort_by(&:index)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.survey = @survey
    @question.index = survey_index

    respond_to do |format|
      if @question.save
        format.html { redirect_to customer_survey_path(@customer, @survey), notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to customer_survey_path(@customer, @survey), notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    index = @question.index
    @question.destroy
    update_indicies @question.index
    respond_to do |format|
      format.html { redirect_to customer_survey_path(@customer, @survey), notice: "Question was deleted" }
      format.json { head :no_content }
    end
  end

  def up
    question = @survey.questions.where(index: @question.index - 1).first
    @question.index = @survey.questions.size + 1
    @question.save!

    question.index = question.index + 1
    question.save!

    @question.index = question.index - 1
    @question.save!

    respond_to do |format|
      format.html {redirect_to customer_survey_path(@customer, @survey), notice: 'Question was successfully moved up.'}
      format.json { head :no_content }
    end
  end

  def down
    question = @survey.questions.where(index: @question.index + 1).first
    @question.index = @survey.questions.size + 1
    @question.save!

    question.index = question.index - 1
    question.save!

    @question.index = question.index + 1
    @question.save!

    respond_to do |format|
      format.html {redirect_to customer_survey_path(@customer, @survey), notice: 'Question was successfully moved down.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      set_type_to_param
      params.require(:question).permit(:text, :index, :survey_id, :yes_no, :rating, :free_form, :customized, :custom_values, :custom_type)
    end

    def set_type_to_param
      if params[:question][:button_type]
        params[:question][params[:question][:button_type].to_s] = true
      end
    end

    def set_survey
      @survey = Survey.find(params[:survey_id])
      @customer = current_user.admin? ? @survey.customer : current_user.customer
      raise unless @survey.customer == @customer
    end

    def survey_index
      Question.where(survey_id: @survey.id).size + 1
    end

  def update_indicies index
    @survey.questions.each do |question|
      if question.index > index
        question.index = question.index - 1
        question.save!
      end
    end
  end

end

app/views/questions/_form.html.erb
<%= form_for([@customer, @survey, @question]) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text, "This is the text displayed to your customers.  Include here punctuation as you wish it to appear." %><br />
    <%= f.text_area :text %>
  </div>

  <div class="field">
    <%= f.label "Question Type:" %>
    <br />
    &nbsp;<%= f.radio_button :yes_no, :yes_no, { name: "question[button_type]", class: "qtype", checked: @question.yes_no?} %>
    Yes/No<br />
    &nbsp;<%= f.radio_button :rating, :rating, { name: "question[button_type]", class: "qtype", checked: @question.rating?} %>
    Rating<br />
    &nbsp;<%= f.radio_button :free_form, :free_form, { name: "question[button_type]", class: "qtype", checked: @question.free_form?} %>
    Free Form<br />
    &nbsp;<%= f.radio_button :customized, :customized, { name: "question[button_type]", class: "qtype", checked: @question.customized?} %>
    Customized<br />
  </div>
  <div class="customized_question">
    <div class="field">
      <%= f.label :custom_values %><br />
      <%= f.text_area :custom_values %>
    </div>
    <div class="field">
      <%= f.label :custom_type %><br />
      <%= f.select :custom_type, options_for_select(Question.custom_types.map.each_with_index { |v,i|[v.titleize,i]}, @question.custom_type) %>
    </div>
  </div>
  <% if @question.customized? %>
    <script>
        $(".customized_question").show()
    </script>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1>Questions <%=@survey.name%></h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Index</th>
      <th>Yes no</th>
      <th>Rating</th>
      <th>Free form</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.text %></td>
        <td><%= question.index %></td>
        <td><%= question.yes_no %></td>
        <td><%= question.rating %></td>
        <td><%= question.free_form %></td>
        <td><%= link_to 'Show', customer_survey_question_path(@customer, @survey, question) %></td>
        <td><%= link_to 'Edit', edit_customer_survey_question_path(@customer, @survey, question) %></td>
        <td><%= link_to 'Destroy', customer_survey_question_path(@customer, @survey, question), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_customer_survey_question_path(@customer, @survey) %>
| <%= link_to 'Back', customer_survey_path(@customer, @survey) %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<p>
  <strong>Index:</strong>
  <%= @question.index %>
</p>

<p>
  <strong>Yes no:</strong>
  <%= @question.yes_no %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @question.rating %>
</p>

<p>
  <strong>Free form:</strong>
  <%= @question.free_form %>
</p>

<%= link_to 'Edit', edit_customer_survey_question_path(@customer, @survey, @question) %> |
<%= link_to 'Back', customer_survey_questions_path(@customer, @survey) %>