config/routes.rb
CrazyJake::Application.routes.draw do

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, except: [:show]

  resources :complete_surveys, only: [:index, :create]

  resources :qr_codes, only: [:index]

  resources :customers do
    resources :surveys do
        member do
          post "card"
        end
      resources :reports, only: [:index]  do
        member do
          post 'reporting_fields'
        end
      end
      resources :questions do
        member do
          get 'down'
          get 'up'
        end
      end
      resources :reporting_fields, except: [:show]
    end
    resources :payments, only: [:index, :create]  do
      member do
        get 'paid'
      end
    end
  end

  root :to => "customers#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable and :omniauthable :confirmable,
  devise :database_authenticatable, :timeoutable, :registerable,
          :rememberable, :trackable, :validatable

  belongs_to :customer

  validates_presence_of :customer_id, unless: :admin?
  validates :email, { uniqueness: true}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_filter :set_user, only: [:show, :update, :edit, :destroy]
  before_filter :set_admin

  def index
    @users = current_user.admin? ? User.all : current_user.master_user? ? User.where(customer_id: current_user.customer.id) : [current_user]
  end

  def new
    @user = User.new
  end

  def create
    if current_user.admin? or current_user.master_user?
      @user = User.new(user_params)
      if !current_user.admin?
        @user.customer = current_user.customer
      end
      @user.sign_in_count = 0
      respond_to do |format|
        if @user.save
          format.html { redirect_to users_path, notice: "#{@user.name} was successfully created." }
          format.json { render action: 'show', status: :created, location: @user }
        else
          format.html { render action: 'new' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url, notice: "You don't have permission to make that change."
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: "#{@user.name} was updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: "#{@user.name} was deleted."}
      format.json { head :no_content }
    end
  end


  private

  def user_params
    if params[:user] and params[:user][:password].blank?
      params[:user].delete :password
    end
    params.require(:user).permit([:email, :customer_id, :admin, :name, :master_user, :password])
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this survey from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <% if @admin %>
    <div class="field">
      <%= f.label :customer_id %><br />
      <%= f.select :customer_id, Customer.all.map{ |c| [c.name, c.id] }, {include_blank: 'None'} %>
    </div>
    <% end %>
    <% if @admin %>
      <div class="field">
        <%= f.label :admin %><br />
        <%= f.check_box :admin %>
      </div>
    <% end %>
    <% if @editable and @user != current_user %>
      <div class="field">
        <%= f.label :master_user %><br />
        <%= f.check_box :master_user %>
      </div>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Sign In Count</th>
    <% if @admin %><th>Administrator</th><% end %>
    <th>Master User</th>
    <th colspan="2">Customer</th>
  </tr>
  </thead>
<% @users.try(:each) do |user| %>
  <tr>
    <td><%= @editable ? (link_to user.name, edit_user_path(user)) : user.name %></td>
    <td><%= @editable ? (link_to user.email, edit_user_path(user)) : user.email %></td>
    <td><%= @editable ? (link_to user.sign_in_count, edit_user_path(user)) : user.sign_in_count %></td>
    <% if @admin %><td><%= link_to user.admin.to_s, edit_user_path(user) %></td><% end %>
    <td><%= @editable ? (link_to user.master_user.to_s, edit_user_path(user)) : user.master_user %></td>
    <td><%= (@editable ? (link_to user.customer.name, customer_path(user.customer)) : user.customer.name) if user.customer%></td>
    <td><%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } if @editable and current_user != user %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New User', new_user_path if @editable %>

app/views/users/new.html.erb
<%= render 'form' %>