config/routes.rb
CrazyJake::Application.routes.draw do

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, except: [:show]

  resources :complete_surveys, only: [:index, :create]

  resources :qr_codes, only: [:index]

  resources :customers do
    resources :surveys do
        member do
          post "card"
        end
      resources :reports, only: [:index]  do
        member do
          post 'reporting_fields'
        end
      end
      resources :questions do
        member do
          get 'down'
          get 'up'
        end
      end
      resources :reporting_fields, except: [:show]
    end
    resources :payments, only: [:index, :create]  do
      member do
        get 'paid'
      end
    end
  end

  root :to => "customers#index"

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :customer
  belongs_to :tracking_type
  has_many :questions, dependent: :destroy
  has_many :reporting_fields, dependent: :destroy
  has_many :complete_surveys, dependent: :destroy

  validates :name, {presence: true, uniqueness: {scope: :customer_id, allow_blank: false }}
  validates :customer_id, { presence: true }
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :card]
  before_filter :set_customer
  before_filter :set_admin
  require 'rqrcode'

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.where(customer_id: @customer.id).sort_by(&:id)
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    #setup_reporting_fields
    rqrcode
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)
    @survey.customer = @customer

    respond_to do |format|
      if @survey.save
        format.html { redirect_to customer_survey_path(@customer,@survey), notice: "#{@survey.name} was successfully created." }
        format.json { render action: 'show', status: :created, location: @survey }
      else
        format.html { render action: 'new' }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to customer_survey_path(@customer,@survey), notice: "#{@survey.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to customer_surveys_path(@customer), notice: "#{@survey.name} was deleted" }
      format.json { head :no_content }
    end
  end

  def card
    if @customer.active? or current_user.admin?
      if params[:what] == "Web Survey"
        p = { survey_id: @survey.id }
        params[:field].try(:each){|k,v| p[("c_" + k).to_sym] = v}
        redirect_to complete_surveys_path(p)
      elsif params[:what] == "Printable Card"
        rqrcode
        @reporting_fields = Hash.new
        params[:field].try(:each){|k,v| @reporting_fields[("c_" + k).to_sym] = v}
        render :pdf => "survey_cards"
      else
        render :blank_card
      end
    else
      render :blank_card
    end
  end

  private

    #def setup_reporting_fields
    #  first_array, *rest = build_values_array
    #  @reporting_fields = first_array.product(*rest) if first_array
    #end

    #def build_values_array
    #  array_holder = Array.new
    #  @survey.reporting_fields.each do |reporting_field,reporting|
    #    iteration_array = Array.new
    #    reporting_field.field_values_array.each_with_index {|value,value_index| iteration_array[value_index] = {"c_" + reporting_field.field_title => value} }
    #    array_holder << iteration_array
    #  end
    #  array_holder
    #end

    def rqrcode
      @qr = RQRCode::QRCode.new(qr_survey_path,:size => 8)
    end

    def set_survey
      set_customer unless @customer
      @survey = Survey.find(params[:id])
      raise unless @survey.customer == @customer
    end

    def qr_survey_path
      input_params = {survey_id: @survey.id}
      params[:field].try(:each){|k,v| input_params[("c_" + k).to_sym] = v}
      complete_surveys_url(input_params)
    end

  # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :customer_id, :complete_message, :tracking_type_id)
    end

    def set_customer
      @customer = current_user.admin? ? Customer.find(params[:customer_id]) : current_user.customer
    end

end

app/views/surveys/_form.html.erb
<%= form_for [@customer, @survey] do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :complete_message %><br />
    <%= f.text_area :complete_message %>
  </div>
  <div class="field">
    <%= f.label :tracking_type_id, "How often can a single user complete this survey?" %><br />
    <%= f.collection_select :tracking_type_id, TrackingType.all, :id, :description, {include_blank: 'No limits'} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_printable.html.erb
<table style="width:6in;height:4.5in;border:1px gray dotted">
  <tr>
    <th colspan='100%'>
      <span style="position: relative; font-size: 40;">
        <%=@customer.name%>
      </span>
    </th>
  </tr>
  <tr>
    <td style="width:4.6in;">
      <table>
        <% @survey.questions.where(free_form: false).order(:index)[0..2].each_with_index do |q, i| %>
            <tr>
              <td><%=i+1%>:</td>
              <td colspan="100%"><%=q.text%></td>
            </tr>
            <% if q.yes_no? %>
                <tr>
                  <td></td>
                  <td colspan="100%">
                    <span style="float:left;font-size:smaller;">Yes</span>
                    <span style="font-size:smaller;margin-left: 100px">No</span>
                  </td>
                </tr>
            <% elsif q.rating? %>
                <tr>
                  <td></td>
                  <td align="center"><input type="radio"></td>
                  <td align="center"><input type="radio"></td>
                  <td align="center"><input type="radio"></td>
                  <td align="center"><input type="radio"></td>
                  <td align="center"><input type="radio"></td>
                </tr>
                <tr>
                  <td></td>
                  <td colspan="100%">
                    <span style="float:left;font-size: smaller; color:#535353;">Extremely Satisfied</span>
                    <span style="float:right;font-size:smaller; color:#535353;">Very Unsatisfied</span>
                  </td>
                </tr>
            <% end %>
        <% end %>
      </table>
    </td>
    <td>
      <table style="border: 1px #f3f3f3 solid;">
        <tr>
          <td colspan="100%"><span style="font-size: x-small;">Date</span></td>
        </tr>
        <tr>
          <td style="border-bottom: 1px solid black;width:25px"></td>
          <td>/</td>
          <td style="border-bottom: 1px solid black;width:25px"></td>
          <td>/</td>
          <td style="border-bottom: 1px solid black;width:25px"></td>
        </tr>
        <tr>
          <td colspan="2">
            <span style="font-size:x-small">Month</span>
          </td>
          <td>
            <span style="font-size:x-small">Day</span>
          </td>
          <td></td>
          <td>
            <span style="font-size:x-small">Year</span>
          </td>
        </tr>
      </table>
      <p />
      <table cellpadding=0 cellspacing=0>
        <% @qr.modules.each_index do |x| %>
            <tr>
              <% @qr.modules.each_index do |y| %>
                  <% if @qr.dark?(x,y) %>
                      <td class="black" style="background-color: black;height:2px; width:2px;"/>
                  <% else -%>
                      <td class="white" style="background-color: white;height:2px;width:2px;"/>
                  <% end %>
              <% end %>
            </tr>
        <% end %>
      </table>
        <% if @reporting_fields %>
          <p />
          <table style="background-color: #f3f3f3">
            <% @reporting_fields.each do |k,v| %>
            <tr>
              <td style="font-size: 8px;">
                <%=k[2,1000]%>:
              </td>
              <td style="font-size: 8px;">
                <%=v%>
              </td>
            </tr>
            <% end %>
          </table>
      <% end %>
    </td>
  </tr>
  <tr>
    <td>
      Comments
    </td>
  </tr>
  <% (1..3).each do %>
      <tr>
        <td colspan="100%">
          <hr style="width:100%"/>
        </td>
      </tr>
  <% end %>
</table>

app/views/surveys/_printable.pdf.erb
<table style="width:6in;height:4.5in;border:1px gray dotted">
  <tr>
    <th colspan='100%'>
      <span style="position: relative; font-size: 40;">
        <%=@customer.name%>
      </span>
    </th>
  </tr>
  <tr>
    <td style="width:4.6in;">
      <table>
        <% @survey.questions.where(free_form: false).order(:index)[0..2].each_with_index do |q, i| %>
            <tr>
              <td><%=i+1%>:</td>
              <td colspan="100%"><%=q.text%></td>
            </tr>
            <% if q.yes_no? %>
                <tr>
                  <td></td>
                  <td colspan="100%">
                    <span style="float:left;font-size:smaller;">Yes</span>
                    <span style="font-size:smaller;margin-left: 100px">No</span>
                  </td>
                </tr>
            <% elsif q.rating? %>
                <tr>
                  <td></td>
                  <td align="center"><input type="radio"></td>
                  <td align="center"><input type="radio"></td>
                  <td align="center"><input type="radio"></td>
                  <td align="center"><input type="radio"></td>
                  <td align="center"><input type="radio"></td>
                </tr>
                <tr>
                  <td></td>
                  <td colspan="100%">
                    <span style="float:left;font-size: smaller; color:#535353;">Extremely Satisfied</span>
                    <span style="float:right;font-size:smaller; color:#535353;">Very Unsatisfied</span>
                  </td>
                </tr>
            <% end %>
        <% end %>
      </table>
    </td>
    <td>
      <table style="border: 1px #f3f3f3 solid;">
        <tr>
          <td colspan="100%"><span style="font-size: x-small;">Date</span></td>
        </tr>
        <tr>
          <td style="border-bottom: 1px solid black;width:25px"></td>
          <td>/</td>
          <td style="border-bottom: 1px solid black;width:25px"></td>
          <td>/</td>
          <td style="border-bottom: 1px solid black;width:25px"></td>
        </tr>
        <tr>
          <td colspan="2">
            <span style="font-size:x-small">Month</span>
          </td>
          <td>
            <span style="font-size:x-small">Day</span>
          </td>
          <td></td>
          <td>
            <span style="font-size:x-small">Year</span>
          </td>
        </tr>
      </table>
      <p />
      <table cellpadding=0 cellspacing=0>
        <% @qr.modules.each_index do |x| %>
            <tr>
              <% @qr.modules.each_index do |y| %>
                  <% if @qr.dark?(x,y) %>
                      <td class="black" style="background-color: black;height:2px; width:2px;"/>
                  <% else -%>
                      <td class="white" style="background-color: white;height:2px;width:2px;"/>
                  <% end %>
              <% end %>
            </tr>
        <% end %>
      </table>
        <% if @reporting_fields %>
          <p />
          <table style="background-color: #f3f3f3">
            <% @reporting_fields.each do |k,v| %>
            <tr>
              <td style="font-size: 8px;">
                <%=k[2,1000]%>:
              </td>
              <td style="font-size: 8px;">
                <%=v%>
              </td>
            </tr>
            <% end %>
          </table>
      <% end %>
    </td>
  </tr>
  <tr>
    <td>
      Comments
    </td>
  </tr>
  <% (1..3).each do %>
      <tr>
        <td colspan="100%">
          <hr style="width:100%"/>
        </td>
      </tr>
  <% end %>
</table>

app/views/surveys/blank_card.html.erb
BLANK

app/views/surveys/blank_card.pdf.erb
<table><tr><td>No Content To Show</td></tr></table>

app/views/surveys/card.html.erb
<table style="width:100%">
  <tr>
    <td align="center">
      <%= render 'printable' %>
    </td>
  </tr>
  <tr>
    <td style="height: 100px;">&nbsp;</td>
  </tr>
  <tr>
    <td align="center">
      <%= render 'printable' %>
    </td>
  </tr>
</table>

app/views/surveys/cards.html.erb
WHAT THE F?

<table style="width:6in;height:4.5in;border:1px gray dotted">

  <tr><th colspan="2"><%=@customer.name%></th></tr>
  <tr>
    <td>
      <table>
        <% @survey.questions.where(free_form: false).each_with_index do |q, i| %>
            <tr>
              <td><%=i+1%>:</td>
              <td colspan="100%"><%=q.text%></td>
            </tr>
            <% if q.yes_no? %>
                <tr>
                  <td></td>
                  <td colspan="100%">
                    <span style="float:left;">Yes</span>
                    <span style="float:right;">No</span>
                  </td>
                </tr>
            <% elsif q.rating? %>
                <tr>
                  <td></td>
                  <td><input type="radio"></td>
                  <td><input type="radio"></td>
                  <td><input type="radio"></td>
                  <td><input type="radio"></td>
                  <td><input type="radio"></td>
                </tr>
                <tr>
                  <td></td>
                  <td colspan="100%">
                    <span style="float:left;">Extremely Satisfied</span>
                    <span style="float:right;">Very Unsatisfied</span>
                  </td>
                </tr>
            <% end %>
        <% end %>
      </table>
    </td>
    <td>
      <table>
        <% @qr.modules.each_index do |x| -%>
            <tr>
              <% @qr.modules.each_index do |y| -%>
                  <% if @qr.dark?(x,y) -%>
                      <td class="black" style="background-color: black;"/>
                  <% else -%>
                      <td class="white" style="background-color: white;"/>
                  <% end -%>
              <% end -%>
            </tr>
        <% end -%>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      Comments
    </td>
  </tr>
  <% (1..4).each do %>
    <tr>
      <td colspan="100%">
        <hr style="width:100%"/>
      </td>
    </tr>
  <% end %>
</table>

app/views/surveys/edit.html.erb
<h1><%= @survey.name %></h1>

<%= render 'form' %>

app/views/surveys/index.html.erb
<h1>Listing surveys</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of questions</th>
      <th colspan="2">Number of Reporting Fields</th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= link_to survey.name, customer_survey_path(@customer, survey) %></td>
        <td><%= survey.questions.size %></td>
        <td><%= survey.reporting_fields.size %></td>
        <td><%= link_to 'Delete', customer_survey_path(@customer,survey), method: :delete, data: { confirm: 'Are you sure?' } if @editable%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

app/views/surveys/show.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th colspan="100%">
        <%= @editable ? (link_to @survey.name, edit_customer_survey_path(@customer, @survey)) : @survey.name %>
      </th>
    </tr>
    <tr>
      <th>Order</th>
      <th>Text</th>
      <th>Question Type</th>
      <% if current_user.admin? or current_user.master_user? %>
      <th>Move Up/Down</th>
      <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @survey.questions.order(:index).each do |question| %>
  <tr>
    <td>
      <div class="divLink">
        <%= question.index %>
      </div>
    </td>
    <td>
      <div class="divLink">
        <%= question.text %>
      </div>
    </td>
    <td>
      <div class="divLink">
        <%= question.yes_no? ? "Yes/No" : question.rating? ? "Rating" : "Free Form" %>
      </div>
    </td>
    <% if current_user.admin? or current_user.master_user? %>
    <td>
      <% if question.index > 1 %>
        <%= link_to '&uarr;'.html_safe, up_customer_survey_question_path(@customer,@survey,question) %>
      <% end %>
      <% if question.index < @survey.questions.size %>
        <%= link_to "&darr;".html_safe, down_customer_survey_question_path(@customer,@survey,question) %>
      <% end %>

    </td>
    <td>
      <%= link_to 'Edit', edit_customer_survey_question_path(@customer,@survey,question)%> |
      <%= link_to 'Delete', customer_survey_question_path(@customer,@survey,question), method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
    <%end%>
  </tr>
  <% end %>
  <% if @editable %>
  <tr>
    <td colspan="100%">
      <%= link_to 'New Question', new_customer_survey_question_path(@customer, @survey) %>
    </td>
  </tr>
  <% end %>
  <tr>
    <td>
      <div class="divLink">
        <%= @editable ? (link_to "Completed Message:", edit_customer_survey_path(@customer, @survey)) : "Completed Message" %>
      </div>
    </td>
    <td>
      <div class="divLink">
      <pre>
<%= @editable ? (link_to @survey.complete_message, edit_customer_survey_path(@customer, @survey)) : @survey.complete_message %>
      </pre>
      </div>
    </td>
  </tr>
  </tbody>
  </table>
</div>
<div class="table-responsive">
  <table class="table table-bordered table-condensed">
    <tbody>
    <tr>
      <th width="10%">User Restrictions</th>
        <% if @survey.tracking_type %>
          <td><%= @editable ? (link_to @survey.tracking_type.description, edit_customer_survey_path(@customer, @survey)) : @survey.tracking_type.description %></td>
        <% else %>
          <td><%= @editable ? (link_to "No Restrictions", edit_customer_survey_path(@customer, @survey)) : "No Restrictions" %></td>
      <% end %>
    </tr>
    </tbody>
  </table>
</div>
<% if @customer.active? or current_user.admin? %>
<div class="table-responsive">
  <form action="<%= card_customer_survey_path%>" method="post">
  <%= form_tag(card_customer_survey_path(@customer, @survey), method: :post) %>
  <table class="table">
    <tbody>
      <% current_value = "" %>
      <% @survey.reporting_fields.each do |reporting_field| %>
        <tr>
          <th width="10%">
            <%= reporting_field.field_title %>
          </th>
          <td>
            <%= select(:field, reporting_field.field_title,reporting_field.field_values_array, { :include_blank => true } ) %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td colspan="100%">
          <%= submit_tag "Printable Card", name: "what" %>
          <%= submit_tag "Web Survey", name: "what" %>
          <input type="reset" value="Clear All Fields" />
        </td>
      </tr>
    </tbody>
  </table>
  </form>
</div>
<% else %>
 <div class="table-responsive">
   <table class="table table-bordered table-condensed">
     <thead>
     <tr>
       <th colspan="100%">Reporting Fields</th>
     </tr>
     <tr>
       <th>Title</th>
       <th>Values</th>
     </tr>
     </thead>
     <tbody>
     <% @survey.reporting_fields.each do |reporting_field| %>
       <tr>
         <td><%=reporting_field.field_title %></td>
         <td><pre><%=reporting_field.field_values%></pre></td>
       </tr>
     <% end %>
     </tbody>
   </table>
 </div>
<% end %>