config/routes.rb
CrazyJake::Application.routes.draw do

  #devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, except: [:show]

  resources :complete_surveys, only: [:index, :create]

  resources :qr_codes, only: [:index]

  resources :customers do
    resources :surveys do
        member do
          post "card"
        end
      resources :reports, only: [:index]  do
        member do
          post 'reporting_fields'
        end
      end
      resources :questions do
        member do
          get 'down'
          get 'up'
        end
      end
      resources :reporting_fields, except: [:show]
    end
    resources :payments, only: [:index, :create]  do
      member do
        get 'paid'
      end
    end
  end

  root :to => "customers#index"

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%
 if @customer or @survey
    c = @customer ? @customer : @survey.customer
 elsif current_user and current_user.customer and current_user.customer.present?
   c = current_user.customer
 end
 c = nil unless c == nil or c.persisted?
 style_str = "background-color:#{c.present? and c.menu_bg_color.present? ?  c.menu_bg_color : '#000000'};color:#{c.present? and c.menu_text_color.present? ? c.menu_text_color :  '#FFFFFF'};"
%>
<style>
  .navbar-link
  {
      background-color:<%= (c.present? and c.menu_bg_color.present?) ?  c.menu_bg_color : '#000000' %>;
      color:<%= (c.present? and c.menu_text_color.present?) ? c.menu_text_color :  '#FFFFFF' %>;
  }

  body, table, a,a:visited, a:active, main{
      background-color: <%=c.present? and c.body_bg_color.present? ? c.body_bg_color : 'white' %>;
      color: <%= c.present? and c.body_text_color.present? ? c.body_text_color : 'black' %>;
  }
  .dropdown{
      font-size: 11px;
  }
</style>
<table width="100%" style="<%=style_str%>">
  <tr>
    <% if c%>
      <td width="10px">
        <% if c.logo? %>
          <%= image_tag c.logo.url(:icon) %>
        <% end %>
      </td>
      <td>
        <h4>
          <%= c.name %>
        </h4>
      </td>
    <% end %>
    <% if user_signed_in? %>
      <td>
        <div class="navbar-text pull-right">
          Welcome <strong><%= current_user.name.present? ? current_user.name : current_user.email %></strong>.
        </div>
      </td>


        <td width="101px">
          <nav class="navbar-default" role="navigation">
            <div class="navbar-header">
              <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" data-toggle="dropdown" style="<%=style_str%>">
                    <%=current_user.name %>
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li style="<%=style_str%>">
                      <%= link_to current_user.admin? ? "All Users" : "Profile", users_path, class: "navbar-link", style: style_str %>
                    </li>
                    <% if current_user.admin? %>
                      <li style="<%=style_str%>">
                        <%= link_to "New User", new_user_path, class: "navbar-link", style: style_str %>
                      </li>
                      <li style="<%= style_str %>">
                        <%= link_to "All Customers", customers_path, class: "navbar-link", style: style_str %>
                      </li>
                            <li>
                              <%= link_to "New Customer", new_customer_path, class: "navbar-link", style: style_str %>
                            </li>
                        <li class="divider"></li>
                    <% end %>
                    <li>
                      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link', style: style_str  %>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </nav>
        </td>


      <% if c %>
      <td width="101px">
        <nav class="navbar-default" role="navigation">
          <div class="navbar-header">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" style="<%=style_str%>">
                  Company
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li>
                      <%= link_to "Profile", customer_path(c), class: "navbar-link", style: style_str %>
                    </li>
                    <% if current_user.admin? or current_user.master_user? %>
                      <li>
                        <%= link_to "Edit", edit_customer_path(c), class: "navbar-link", style: style_str %>
                      </li>
                      <li>
                        <%= link_to "Add User", new_user_path, class: "navbar-link", style: style_str %>
                      </li>
                      <% if !c.active? %>
                      <li>
                        <%= link_to "Make Payment", customer_payments_path(c), class: "navbar-link", style: style_str %>
                      </li>
                      <% end %>
                    <% end %>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
        </td>
        <td width="100px">
          <nav class="navbar-default" role="navigation">
            <div class="navbar-header">
              <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="<%=style_str%>">
                    Surveys
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to "All Surveys", customer_surveys_path(c), class: "navbar-link", style: style_str %>
                    </li>
                    <% c.surveys.each do |survey| %>
                      <li role="presentation" class="dropdown-header" style="<%style_str%>">
                        <%=survey.name%>
                      </li>
                      <li>
                        <%= link_to "View", customer_survey_path(c,survey), class: "navbar-link", style: style_str %>
                      </li>
                      <% if current_user.admin? or current_user.master_user? %>
                      <li>
                        <%= link_to "Edit", edit_customer_survey_path(c,survey), class: "navbar-link", style: style_str %>
                      </li>
                      <li>
                        <%= link_to "Reporting Fields", customer_survey_reporting_fields_path(c,survey), class: "navbar-link", style: style_str %>
                      </li>
                    <% end %>
                    <li class="divider"></li>
                    <% end %>
                    <% if current_user.admin? or current_user.master_user? %>
                      <li>
                        <%= link_to "Create new survey", new_customer_survey_path(c), class: "navbar-link", style: style_str %>
                      </li>
                    <% end %>
                  </ul>
                </li>
              </ul>
            </div>
          </nav>
          </td>
          <% if c.active? or (current_user and current_user.admin?) %>
          <td width="100px">
            <nav class="navbar-default" role="navigation">
              <div class="navbar-header">
                <ul class="nav navbar-nav">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="<%=style_str%>">
                      Reports
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <% c.surveys.each do |survey| %>
                          <li>
                            <!-- link_to survey.name, customer_survey_reports_path(c,survey,format: 'pdf'),target: "_blank", class: "navbar-link", style: style_str -->
                            <%= link_to survey.name, customer_survey_reports_path(c,survey,format: 'html'), class: "navbar-link", style: style_str %>
                          </li>
                      <% end %>
                    </ul>
                  </li>
                </ul>
              </div>
            </nav>
          </td>
          <% end %>
        <% end %>
      <% end %>
    <td width="100px">&nbsp;</td>
  </tr>
</table>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Survey Site" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Crazy Jake" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "https://js.stripe.com/v1/", "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= tag :meta, :name => "stripe-key", content: STRIPE_PUBLIC_KEY %>
    <!-- Google Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-47452960-1', 'calm-falls-8861.herokuapp.com');
        ga('send', 'pageview');

    </script>
    <!-- END Google Analytics -->
  </head>
  <body>
    <header style="height: 20px;">
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>